#!/bin/bash
water_base=ewwatratewa
stir_base=ti.itirtrtr
bestchol_base=shtbeolhc
water_decimal=$(echo "$WATER" | tr "$water_base" '0123456789' | bc)
stir_decimal=$(echo "$STIR" | tr "$stir_base" '0123456789' | bc)
sum_decimal=$(($water_decimal + $stir_decimal))
echo "$sum_decimal" | tr '0123456789' "$bestchol_base"
